version: '3'

services:
  prefect-database:
    image: postgres:15.2-alpine
    container_name: prefect-database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes:
      - database:/var/lib/postgresql/data

  prefect-server:
    image: prefecthq/prefect:2.8.0-python3.10
    container_name: prefect-server
    restart: always
    command: prefect orion start
    ports:
      - 4200:4200
    volumes:
      - prefect:/root/.prefect
    environment:
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_ORION_API_HOST=0.0.0.0
      - PREFECT_ORION_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@prefect-database:5432/prefect
    depends_on:
      - prefect-database

  prefect-agent:
    image: prefecthq/prefect:2.8.0-python3.10
    container_name: prefect-agent
    restart: always
    command: >
      bash -c "pip install -r /requirements.txt
      && prefect agent start --pool default-agent-pool --work-queue default"
    volumes:
      - ./flows:/root/flows
      - ./requirements.txt:/requirements.txt
      - mlflow:/mlflow
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api

  prefect-cli:
    image: prefecthq/prefect:2.8.0-python3.10
    container_name: prefect-cli
    command: >
      bash -c "pip install -r /requirements.txt
      && tail -f /dev/null"
    working_dir: /root/flows
    volumes:
      - ./flows:/root/flows
      - ./requirements.txt:/requirements.txt
    environment:
      - PREFECT_API_URL=http://prefect-server:4200/api

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.1.1
    container_name: mlflow
    restart: always
    command: mlflow server --backend-store-uri sqlite:////mlflow/mlflow.db --default-artifact-root /mlflow/artifacts --artifacts-destination /mlflow/artifacts --host 0.0.0.0
    ports:
      - 5000:5000
    volumes:
      - mlflow:/mlflow

  api:
    build: ./fastapi
    container_name: api
    restart: always
    depends_on:
      - mlflow
    ports:
      - 8080:80
    volumes:
      - mlflow:/mlflow
    environment:
      - MLFLOW_URI=http://mlflow:5000
      - MODEL_URI=models:/linear_regression/production

volumes:
  mlflow:
  database:
  prefect:

networks:
  default:
    name: mlops
